# .github/workflows/deploy.yml

name: EC2로 자동배포하기

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2 접속하기
        uses: appleboy/ssh-action@v1
        env:
          # ENV라는 변수에 github secrets에 저장된 ENV 값을 넣어준다.
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          # 위에서 등록한 ENV 변수를 EC2 서버로 전달한다.
          envs: ENV
          script: |
            set -e
            cd /home/ubuntu/nextjs-aws-test 
            rm -rf .env 
            git pull origin main
            # 루트 경로에 .env 파일을 만든다.
            echo "$ENV" > .env
            pm2 kill
            npm ci
            npm run build
            pm2 start npm --name "nextjs-app" -- start
